STAMPS = {
    "happy" : {
        "name": "Happy",
        "stamp": url_for("static", filename="stamps/mood/happy.png"),
        "icon": url_for("static", filename="icons/mood/happy.svg"),
        "label": _("嬉しい"),
        "description": _("Feeling happy and joyful."),
        "order": 1,
    },
    "fun" : {
        "name": "Fun",
        "stamp": url_for("static", filename="stamps/mood/fun.png"),
        "icon": url_for("static", filename="icons/mood/fun.svg"),
        "label": _("楽しい"),
        "description": _("Having fun and enjoying the moment."),
        "order": 2,
    },
    "sad" : {
        "name": "Sad",
        "stamp": url_for("static", filename="stamps/mood/sad.png"),
        "icon": url_for("static", filename="icons/mood/sad.svg"),
        "label": _("悲しい"),
        "description": _("Feeling sad and down."),
        "order": 3,
    },
    "angry" : {
        "name": "Angry",
        "stamp": url_for("static", filename="stamps/mood/angry.png"),
        "icon": url_for("static", filename="icons/mood/angry.svg"),
        "label": _("怒っている"),
        "description": _("Feeling angry and frustrated."),
        "order": 4,
    },
    "lonely" : {
        "name": "Lonely",
        "stamp": url_for("static", filename="stamps/mood/lonely.png"),
        "icon": url_for("static", filename="icons/mood/lonely.svg"),
        "label": _("寂しい"),
        "description": _("Feeling lonely and isolated."),
        "order": 5,
    },
    "scared" : {
        "name": "Scared",
        "stamp": url_for("static", filename="stamps/mood/scared.png"),
        "icon": url_for("static", filename="icons/mood/scared.svg"),
        "label": _("こわい"),
        "description": _("Feeling scared and anxious."),
        "order": 6,
    },
}